version: "3.8"

services:
    mysql:
        image: mysql:8
        restart: always
        container_name: laravel_db3
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
        ports:
        - "33064:3306"
        volumes:
            - ./docker/dev/tmp/db:/var/lib/mysql

    app:
        build:
            context: .
            dockerfile: docker/dev/Dockerfile

        ports:
            - "8084:80"
        volumes:
            - .:/var/www/html





